package com.myapp.domain.model

data class Vocabulary(
    val id: String,
    val hiragana: String,
    val katakana: String? = null,
    val kanji: String? = null,
    val romaji: String,
    val frenchTranslation: String,
    val englishTranslation: String,
    val exampleSentence: String? = null,
    val exampleTranslation: String? = null,
    val jlptLevel: String? = null,
    val categoryId: String? = null,
    val categoryName: String? = null,
    val pitchAccent: String? = null,
    val tags: List<String> = emptyList(),
    val hasAudio: Boolean = false,
    val audioUrl: String? = null,
    val isActive: Boolean = true,
    val successCount: Int = 0,
    val failureCount: Int = 0,
    val easeFactor: Double = 2.5,
    val intervalDays: Int = 0,
    val repetitions: Int = 0,
    val nextReviewAt: Double? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
)
